Erase legacy genesis DB
Fantom-foundation/go-opera pull request #316
Opened 2022-05-20 09:42 UTC by uprendis

- add migration for erasing legacy genesis DB to avoid issues with non-closed genesis DB

2022-05-20 10:38 UTC, hadv requested changes

2022-05-20 10:38 UTC, hadv commented on gossip/store_migration.go
> +	gossipDB, err := s.dbs.OpenDB("genesis")
just a naming 

```suggestion
	genesisDB, err := s.dbs.OpenDB("genesis")
```

2022-05-20 19:52 UTC, cyberbono3 approved these changes

2022-05-21 01:58 UTC, hadv approved these changes

2022-05-21 14:30 UTC, rus-alex approved these changes

2022-05-24 11:20 UTC, merged